apiVersion: profiles.fluxcd.io/v1alpha1
kind: Profile
metadata:
  name: nginx
spec:
  description: Profile for deploying nginx
  version: v0.0.1
  artifacts:
    - name: nginx-server
      path: nginx/chart
      kind: HelmChart
    - name: nginx-deployment
      path: nginx/deployment
      kind: Kustomize
    - name: dokuwiki
      kind: HelmChart
      chart:
        helm_url: https://charts.bitnami.com/bitnami
        helm_chart: dokuwiki
        helm_chart_version: "11.1.6"
